version: "3"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
     - traefik-public
    labels:
      traefik.http.services.dashboard.loadbalancer.server.port: '9090'
      traefik.http.routers.dashboard.rule: (Host(`api.opengate.lan`) && PathPrefix(`/api/v1`))
      traefik.http.routers.dashboard.entrypoints: web
      traefik.enable: 'true'
      traefik.http.routers.dashboard.service: dashboard
    volumes:
      - "/etc/sr/dashboard/data/prometheus.yml:/etc/prometheus/prometheus.yml"
    restart: always
  nodeexporter:
    image: prom/node-exporter
    container_name: nodeexporter
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: always
networks:
  traefik-public:
    external: true
